name: obliterate all folders via ssh
on:
  workflow_dispatch: 

jobs:
  ssh:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Interactive SSH Session
        uses: mxschmitt/action-tmate@v3
        timeout-minutes: 60 
